# Generated by Django 2.2.7 on 2019-11-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagenes',
            field=models.ImageField(upload_to='documents'),
        ),
    ]
