# Generated by Django 2.2.7 on 2019-11-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exo', '0002_auto_20191117_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagenes',
            field=models.ImageField(null=True, upload_to='documents'),
        ),
    ]
